model: logreg
target: target
split_mode: time
seed: 42
feature_set: adsb_only
features:
  numeric:
    - n_approaches
    - n_rwy_approached
    - glide_slope_angle
    - rwy_length
    - month
    - day_of_week
    - hour_utc
  categorical:
    - airport
    - runway
    - typecode
    - icaoaircrafttype
    - wtc
    - has_intersection
    - airport_country
    - airport_region
    - operator_country
    - operator_region
